version: '3.1'

services:
  app:
    # build: ./docker.page
    image: extsand/academy_docker.page:latest
    restart: always
    ports:
      - ${APP_PORT}:80
  
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    # depends_on:
    #   - db

    env_file: .env


    
