version: '3.1'

services:
  app:
    build: ./docker.page
    # image: myDo
    restart: always
    ports:
      - 9999:80
  
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    # depends_on:
    #   - db


    
